audit_header: false
title: "Guaranteed Offer"
description: Rob Kittle, a top Real Estate Agent in Northern Colorado, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
client:
  name: Rob Kittle
  title:
  license_number:
  about_markdown: |

  market: Northern Colorado
  brand: Kittle Real Estate
  brokerage:
  address: 300 S Howes St Fort Collins, CO 80521
  phone: 970-460-4444
  phone_type:
  phone2:
  phone2_type:
  email: contact@kittleteam.com
  url: https://www.kittlerealestate.com

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#AF102C'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
